require "yaml"

config_file = YAML.load_file(
  File.join(File.dirname(__FILE__), "config.yml")
)

instance_count = config_file["instance_count"]

vm_config = config_file["vm"]
resources = config_file["resources"]
network = config_file["network"]

Vagrant.configure("2") do |config|

  config.vm.box = vm_config["box"]

  (1..instance_count).each do |i|

    vm_name = "#{vm_config["name_prefix"]}-#{format('%02d', i)}"
    hostname = "#{vm_config["hostname_prefix"]}-#{format('%02d', i)}"
    ip_address = "#{network["base_ip"]}.#{network["start_ip"] + i - 1}"

    config.vm.define vm_name do |node|

      node.vm.hostname = hostname

      node.vm.network "private_network",
        ip: ip_address

      node.vm.provider "virtualbox" do |vb|

        vb.name = vm_name
        vb.memory = resources["memory"]
        vb.cpus = resources["cpus"]

      end

      node.vm.provision "shell",
        path: "scripts/setup.sh"

    end

  end

end